<?php $MySQL = new mysqli('localhost', 'ADMIN', 'PASSWORD', 'DATABASE');
    $alphabet = array("a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z");
    $topsites[0] = "google.com"; 
    $topsites[1] = "facebook.com"; 
    $topsites[2] = "youtube.com"; 
    $topsites[3] = "amazon.com"; 
    $topsites[4] = "yahoo.com"; 
    $topsites[5] = "wikipedia.org"; 
    $topsites[6] = "ebay.com"; 
    $topsites[7] = "twitter.com"; 
    $topsites[8] = "reddit.com"; 
    $topsites[9] = "linkedin.com"; 
    $topsites[10] = "netflix.com"; 
    $topsites[11] = "craigslist.org"; 
    $topsites[12] = "pinterest.com"; 
    $topsites[13] = "live.com"; 
    $topsites[14] = "bing.com"; 
    $topsites[15] = "imgur.com"; 
    $topsites[16] = "go.com"; 
    $topsites[17] = "instagram.com"; 
    $topsites[18] = "chase.com"; 
    $topsites[19] = "diply.com"; 
    $topsites[20] = "paypal.com"; 
    $topsites[21] = "tumblr.com"; 
    $topsites[22] = "msn.com"; 
    $topsites[23] = "cnn.com"; 
    $topsites[24] = "bankofamerica.com"; 
    $topsites[25] = "espn.com"; 
    $topsites[26] = "zillow.com"; 
    $topsites[27] = "t.co"; 
    $topsites[28] = "imdb.com"; 
    $topsites[29] = "wellfargo.com"; 
    $topsites[30] = "walmart.com"; 
    $topsites[31] = "nytimes.com"; 
    $topsites[32] = "blogspot.com"; 
    $topsites[33] = "yelp.com"; 
    $topsites[34] = "weather.com"; 
    $topsites[35] = "office.com"; 
    $topsites[36] = "apple.com"; 
    $topsites[37] = "homedepot.com"; 
    $topsites[38] = "aol.com"; 
    $topsites[39] = "wordpress.com"; 
    $topsites[40] = "comcast.net"; 
    $topsites[41] = "microsoftonline.com"; 
    $topsites[42] = "etsy.com"; 
    $topsites[43] = "microsoft.com"; 
    $topsites[44] = "huffingtonpost.com"; 
    $topsites[45] = "target.com"; 
    $topsites[46] = "foxnews.com"; 
    $topsites[47] = "washingtonpost.com"; 
    $topsites[48] = "wikia.com"; 
    $topsites[49] = "buzzfeed.com"; 
    $topsites[50] = "xfinity.com"; 
    $topsites[51] = "dropbox.com"; 
    $topsites[52] = "capitalone.com"; 
    $topsites[53] = "indeed.com"; 
    $topsites[54] = "pornhub.com"; 
    $topsites[55] = "outbrain.com"; 
    $topsites[56] = "tripadvisor.com"; 
    $topsites[57] = "salesforce.com"; 
    $topsites[58] = "pandora.com"; 
    $topsites[59] = "gfycat.com"; 
    $topsites[60] = "hulu.com"; 
    $topsites[61] = "bestbuy.com"; 
    $topsites[62] = "americanexpress.com"; 
    $topsites[63] = "usps.com"; 
    $topsites[64] = "groupon.com"; 
    $topsites[65] = "googleusercontent.com"; 
    $topsites[66] = "slickdeals.net"; 
    $topsites[67] = "stackoverflow.com"; 
    $topsites[68] = "github.com"; 
    $topsites[69] = "twitch.tv"; 
    $topsites[70] = "lowes.com"; 
    $topsites[71] = "att.com"; 
    $topsites[72] = "ups.com"; 
    $topsites[73] = "vice.com"; 
    $topsites[74] = "force.com"; 
    $topsites[75] = "citi.com"; 
    $topsites[76] = "adobe.com"; 
    $topsites[77] = "usatoday.com"; 
    $topsites[78] = "verizonwireless.com"; 
    $topsites[79] = "xvideos.com"; 
    $topsites[80] = "godaddy.com"; 
    $topsites[81] = "mlb.com"; 
    $topsites[82] = "cnet.com"; 
    $topsites[83] = "fedex.com"; 
    $topsites[84] = "forbes.com"; 
    $topsites[85] = "dailymail.co.uk"; 
    $topsites[86] = "kat.cr"; 
    $topsites[87] = "macys.com"; 
    $topsites[88] = "intuit.com"; 
    $topsites[89] = "kohls.com"; 
    $topsites[90] = "quora.com"; 
    $topsites[91] = "amazonaws.com"; 
    $topsites[92] = "realtor.com"; 
    $topsites[93] = "ancestry.com"; 
    $topsites[94] = "discovercard.com"; 
    $topsites[95] = "lifebuzz.com"; 
    $topsites[96] = "conservativetribune.com"; 
    $topsites[97] = "bbc.com"; 
    $topsites[98] = "instructure.com"; 
    $topsites[99] = "ask.com"; 
    $topsites[100] = "businessinsider.com"; 
    $topsites[101] = "gizmodo.com"; 
    $topsites[102] = "webmd.com"; 
    $topsites[103] = "costco.com"; 
    $topsites[104] = "usaa.com"; 
    $topsites[105] = "taboola.com"; 
    $topsites[106] = "nih.gov"; 
    $topsites[107] = "soundcloud.com"; 
    $topsites[108] = "trulia.com"; 
    $topsites[109] = "spotify.com"; 
    $topsites[110] = "southwest.com"; 
    $topsites[111] = "expedia.com"; 
    $topsites[112] = "feedly.com"; 
    $topsites[113] = "patch.com"; 
    $topsites[114] = "xhamster.com"; 
    $topsites[115] = "ca.gov"; 
    $topsites[116] = "wunderground.com"; 
    $topsites[117] = "fidelity.com"; 
    $topsites[118] = "about.com"; 
    $topsites[119] = "vimeo.com"; 
    $topsites[120] = "gap.com"; 
    $topsites[121] = "nordstrom.com"; 
    $topsites[122] = "goodreads.com"; 
    $topsites[123] = "accuweather.com"; 
    $topsites[124] = "wayfair.com"; 
    $topsites[125] = "theguardian.com"; 
    $topsites[126] = "flickr.com"; 
    $topsites[127] = "airbnb.com"; 
    $topsites[128] = "deviantart.com"; 
    $topsites[129] = "netteller.com"; 
    $topsites[130] = "ebates.com"; 
    $topsites[131] = "newegg.com"; 
    $topsites[132] = "adp.com"; 
    $topsites[133] = "wsj.com"; 
    $topsites[134] = "onclickads.net"; 
    $topsites[135] = "drudgereport.com"; 
    $topsites[136] = "stackexchange.com"; 
    $topsites[137] = "nbcnews.com"; 
    $topsites[138] = "verizon.com"; 
    $topsites[139] = "abcnews.com"; 
    $topsites[140] = "overstock.com"; 
    $topsites[141] = "woot.com"; 
    $topsites[142] = "kayak.com"; 
    $topsites[143] = "blackboard.com"; 
    $topsites[144] = "usbank.com"; 
    $topsites[145] = "retailmenot.com"; 
    $topsites[146] = "pch.com"; 
    $topsites[147] = "allrecipes.com"; 
    $topsites[148] = "aa.com"; 
    $topsites[149] = "zulily.com"; 
    $topsites[150] = "thesaurus.com"; 
    $topsites[151] = "blogger.com"; 
    $topsites[152] = "taleo.net"; 
    $topsites[153] = "wittyfeed.com"; 
    $topsites[154] = "quizlet.com"; 
    $topsites[155] = "redfin.com"; 
    $topsites[156] = "people.com"; 
    $topsites[157] = "npr.org"; 
    $topsites[158] = "delta.com"; 
    $topsites[159] = "latimes.com"; 
    $topsites[160] = "ticketmaster.com"; 
    $topsites[161] = "weebly.com"; 
    $topsites[162] = "cbsnews.com"; 
    $topsites[163] = "sears.com"; 
    $topsites[164] = "ign.com"; 
    $topsites[165] = "glassdoor.com"; 
    $topsites[166] = "nextdoor.com"; 
    $topsites[167] = "creditkarma.com"; 
    $topsites[168] = "putlocker.is"; 
    $topsites[169] = "ozock.com"; 
    $topsites[170] = "weather.gov"; 
    $topsites[171] = "jcpenney.com"; 
    $topsites[172] = "steamcommunity.com"; 
    $topsites[173] = "ikea.com"; 
    $topsites[174] = "myway.com"; 
    $topsites[175] = "searchincognito.com"; 
    $topsites[176] = "txxx.com"; 
    $topsites[177] = "lifehacker.com"; 
    $topsites[178] = "hclips.com"; 
    $topsites[179] = "sharepoint.com"; 
    $topsites[180] = "wikihow.com"; 
    $topsites[181] = "baidu.com"; 
    $topsites[182] = "bloomberg.com"; 
    $topsites[183] = "answers.com"; 
    $topsites[184] = "icloud.com"; 
    $topsites[185] = "box.com"; 
    $topsites[186] = "bleacherreport.com"; 
    $topsites[187] = "surveymonkey.com"; 
    $topsites[188] = "united.com"; 
    $topsites[189] = "hgtv.com"; 
    $topsites[190] = "myfitnesspal.com"; 
    $topsites[191] = "roblox.com"; 
    $topsites[192] = "westernjournalism.com"; 
    $topsites[193] = "mint.com"; 
    $topsites[194] = "staples.com"; 
    $topsites[195] = "fitbit.com"; 
    $topsites[196] = "slate.com"; 
    $topsites[197] = "webex.com"; 
    $topsites[198] = "walgreens.com"; 
    $topsites[199] = "pinimg.com"; 
    $topsites[200] = "kickstarter.com"; 
    $topsites[201] = "swagbucks.com"; 
    $topsites[202] = "irs.gov"; 
    $topsites[203] = "pnc.com"; 
    $topsites[204] = "priceline.com"; 
    $topsites[205] = "hbogo.com"; 
    $topsites[206] = "mapquest.com"; 
    $topsites[207] = "houzz.com"; 
    $topsites[208] = "politico.com"; 
    $topsites[209] = "eventbrite.com"; 
    $topsites[210] = "thatviralfeed.com"; 
    $topsites[211] = "constantcontact.com"; 
    $topsites[212] = "thekitchn.com"; 
    $topsites[213] = "foodnetwork.com"; 
    $topsites[214] = "dell.com"; 
    $topsites[215] = "audible.com"; 
    $topsites[216] = "zappos.com"; 
    $topsites[217] = "dmv.org"; 
    $topsites[218] = "dictionary.com"; 
    $topsites[219] = "aliexpress.com"; 
    $topsites[220] = "meetup.com"; 
    $topsites[221] = "nba.com"; 
    $topsites[222] = "buzzlie.com"; 
    $topsites[223] = "nypost.com"; 
    $topsites[224] = "tmz.com"; 
    $topsites[225] = "livejasmin.com"; 
    $topsites[226] = "sfgate.com"; 
    $topsites[227] = "theverge.com"; 
    $topsites[228] = "okcupid.com"; 
    $topsites[229] = "mashable.com"; 
    $topsites[230] = "whitepages.com"; 
    $topsites[231] = "marriott.com"; 
    $topsites[232] = "steampowered.com"; 
    $topsites[233] = "battle.net"; 
    $topsites[234] = "t-mobile.com"; 
    $topsites[235] = "bedbathandbeyond.com"; 
    $topsites[236] = "shopify.com"; 
    $topsites[237] = "samsclub.com"; 
    $topsites[238] = "worldlifestyle.com"; 
    $topsites[239] = "infusionsoft.com"; 
    $topsites[240] = "zendesk.com"; 
    $topsites[241] = "slack.com"; 
    $topsites[242] = "legacy.com"; 
    $topsites[243] = "qvc.com"; 
    $topsites[244] = "pogo.com"; 
    $topsites[245] = "shutterfly.com"; 
    $topsites[246] = "evite.com"; 
    $topsites[247] = "barclaycardus.com"; 
    $topsites[248] = "fandango.com"; 
    $topsites[249] = "nydailynews.com"; 
    $topsites[250] = "cbssports.com"; 
    $topsites[251] = "yellowpages.com"; 
    $topsites[252] = "hotnewwhiphop.com"; 
    $topsites[253] = "slither.io"; 
    $topsites[254] = "squarespace.com"; 
    $topsites[255] = "time.com"; 
    $topsites[256] = "onlinecreditcenter6.com"; 
    $topsites[257] = "cbs.com"; 
    $topsites[258] = "wix.com"; 
    $topsites[259] = "hotels.com"; 
    $topsites[260] = "cvs.com"; 
    $topsites[261] = "gamefaqs.com"; 
    $topsites[262] = "discover.com"; 
    $topsites[263] = "umblr.com"; 
    $topsites[264] = "cnbc.com"; 
    $topsites[265] = "rottentomatoes.com"; 
    $topsites[266] = "likes.com"; 
    $topsites[267] = "popsugar.com"; 
    $topsites[268] = "hilton.com"; 
    $topsites[269] = "media.tumblr.com"; 
    $topsites[270] = "chaturbate.com"; 
    $topsites[271] = "rei.com"; 
    $topsites[272] = "diynetwork.com"; 
    $topsites[273] = "hp.com"; 
    $topsites[274] = "pof.com"; 
    $topsites[275] = "gawker.com"; 
    $topsites[276] = "reddituploads.com"; 
    $topsites[277] = "citibankonline.com"; 
    $topsites[278] = "nametests.com"; 
    $topsites[279] = "engadget.com"; 
    $topsites[280] = "deadspin.com"; 
    $topsites[281] = "eonline.com"; 
    $topsites[282] = "breitbart.com"; 
    $topsites[283] = "gofundme.com"; 
    $topsites[284] = "topix.com"; 
    $topsites[285] = "vrbo.com"; 
    $topsites[286] = "capitalone360.com"; 
    $topsites[287] = "thepiratebay.org"; 
    $topsites[288] = "medium.com"; 
    $topsites[289] = "mayoclinic.com"; 
    $topsites[290] = "kotaku.com"; 
    $topsites[291] = "mailchimp.com"; 
    $topsites[292] = "files.wordpress.com"; 
    $topsites[293] = "iheart.com"; 
    $topsites[294] = "booking.com"; 
    $topsites[295] = "ew.com"; 
    $topsites[296] = "xnxx.com"; 
    $topsites[297] = "coupons.com"; 
    $topsites[298] = "bhphotovideo.com"; 
    $topsites[299] = "popads.net"; 
    $topsites[300] = "wikimedia.org"; 
    $topsites[301] = "list-manage.com"; 
    $topsites[302] = "secureserver.net"; 
    $topsites[303] = "schwab.com"; 
    $topsites[304] = "nike.com"; 
    $topsites[305] = "match.com"; 
    $topsites[306] = "instructables.com"; 
    $topsites[307] = "monster.com"; 
    $topsites[308] = "autotrader.com"; 
    $topsites[309] = "thedailybeast.com"; 
    $topsites[310] = "giphy.com"; 
    $topsites[311] = "redtube.com"; 
    $topsites[312] = "ed.gov"; 
    $topsites[313] = "jet.com"; 
    $topsites[314] = "alibaba.com"; 
    $topsites[315] = "evernote.com"; 
    $topsites[316] = "sephora.com"; 
    $topsites[317] = "timewarnercable.com"; 
    $topsites[318] = "trello.com"; 
    $topsites[319] = "cbslocal.com"; 
    $topsites[320] = "fbcdn.net"; 
    $topsites[321] = "marketwatch.com"; 
    $topsites[322] = "littlethings.com"; 
    $topsites[323] = "kbb.com"; 
    $topsites[324] = "thepennyhoarder.com"; 
    $topsites[325] = "opentable.com"; 
    $topsites[326] = "disney.go.com"; 
    $topsites[327] = "upornia.com"; 
    $topsites[328] = "barnesandnoble.com"; 
    $topsites[329] = "starbucks.com"; 
    $topsites[330] = "sprint.com"; 
    $topsites[331] = "telegraph.co.uk"; 
    $topsites[332] = "vox.com"; 
    $topsites[333] = "stubhub.com"; 
    $topsites[334] = "pbs.org"; 
    $topsites[335] = "comenity.net"; 
    $topsites[336] = "jezebel.com"; 
    $topsites[337] = "theatlantic.com"; 
    $topsites[338] = "icims.com"; 
    $topsites[339] = "fivethirtyeight.com"; 
    $topsites[340] = "bbc.co.uk"; 
    $topsites[341] = "synchronycredit.com"; 
    $topsites[342] = "consumerreports.org"; 
    $topsites[343] = "toysrus.com"; 
    $topsites[344] = "azlyrics.com"; 
    $topsites[345] = "usnews.com"; 
    $topsites[346] = "nbcsports.com"; 
    $topsites[347] = "oracle.com"; 
    $topsites[348] = "chicagotribune.com"; 
    $topsites[349] = "cracked.com"; 
    $topsites[350] = "skype.com"; 
    $topsites[351] = "directv.com"; 
    $topsites[352] = "speedtest.net"; 
    $topsites[353] = "dailymotion.com"; 
    $topsites[354] = "urbandictionary.com"; 
    $topsites[355] = "norton.com"; 
    $topsites[356] = "okta.com"; 
    $topsites[357] = "reuters.com"; 
    $topsites[358] = "concursolutions.com"; 
    $topsites[359] = "biblegateway.com"; 
    $topsites[360] = "secureinternetbank.com"; 
    $topsites[361] = "bongacams.com"; 
    $topsites[362] = "4chan.org"; 
    $topsites[363] = "pixnet.net"; 
    $topsites[364] = "vistaprint.com"; 
    $topsites[365] = "github.io"; 
    $topsites[366] = "youporn.com"; 
    $topsites[367] = "att.net"; 
    $topsites[368] = "wnd.com"; 
    $topsites[369] = "today.com"; 
    $topsites[370] = "tvguide.com"; 
    $topsites[371] = "babycenter.com"; 
    $topsites[372] = "mit.edu"; 
    $topsites[373] = "qualtrics.com"; 
    $topsites[374] = "hbonow.com"; 
    $topsites[375] = "refinery29.com"; 
    $topsites[376] = "ibanking-services.com"; 
    $topsites[377] = "dailykos.com"; 
    $topsites[378] = "officedepot.com"; 
    $topsites[379] = "aarp.org"; 
    $topsites[380] = "bankrate.com"; 
    $topsites[381] = "rollingstone.com"; 
    $topsites[382] = "bp.blogspot.com"; 
    $topsites[383] = "archiveofourown.org"; 
    $topsites[384] = "ecollege.com"; 
    $topsites[385] = "archive.org"; 
    $topsites[386] = "hollywoodreporter.com"; 
    $topsites[387] = "dominos.com"; 
    $topsites[388] = "forever21.com"; 
    $topsites[389] = "victoriassecret.com"; 
    $topsites[390] = "pcmag.com"; 
    $topsites[391] = "4dsply.com"; 
    $topsites[392] = "vanguard.com"; 
    $topsites[393] = "brassring.com"; 
    $topsites[394] = "khanacademy.org"; 
    $topsites[395] = "kinja.com"; 
    $topsites[396] = "smugmug.com"; 
    $topsites[397] = "suntrust.com"; 
    $topsites[398] = "atlassian.net"; 
    $topsites[399] = "gamepedia.com"; 
    $topsites[400] = "abc.go.com"; 
    $topsites[401] = "chron.com"; 
    $topsites[402] = "food.com"; 
    $topsites[403] = "fanfiction.net"; 
    $topsites[404] = "tdbank.com"; 
    $topsites[405] = "jalopnik.com"; 
    $topsites[406] = "gamespot.com"; 
    $topsites[407] = "samsung.com"; 
    $topsites[408] = "gamestop.com"; 
    $topsites[409] = "patheos.com"; 
    $topsites[410] = "ssa.gov"; 
    $topsites[411] = "rr.com"; 
    $topsites[412] = "dickssportinggoods.com"; 
    $topsites[413] = "parentanswercenter.com"; 
    $topsites[414] = "livestrong.com"; 
    $topsites[415] = "cars.com"; 
    $topsites[416] = "kissanime.to"; 
    $topsites[417] = "custhelp.com"; 
    $topsites[418] = "wired.com"; 
    $topsites[419] = "arstechnica.com"; 
    $topsites[420] = "merriam-webster.com"; 
    $topsites[421] = "primewire.ag"; 
    $topsites[422] = "bodybuilding.com"; 
    $topsites[423] = "twimg.com"; 
    $topsites[424] = "si.com"; 
    $topsites[425] = "cinemablend.com"; 
    $topsites[426] = "msnbc.com"; 
    $topsites[427] = "cox.net"; 
    $topsites[428] = "lotterypost.com"; 
    $topsites[429] = "ibm.com"; 
    $topsites[430] = "sheknows.com"; 
    $topsites[431] = "edmunds.com"; 
    $topsites[432] = "navyfederal.org"; 
    $topsites[433] = "cisco.com"; 
    $topsites[434] = "messenger.com"; 
    $topsites[435] = "docusign.net"; 
    $topsites[436] = "squareup.com"; 
    $topsites[437] = "greatergood.com"; 
    $topsites[438] = "realclearpolitics.com"; 
    $topsites[439] = "howtogeek.com"; 
    $topsites[440] = "goodhousekeeping.com"; 
    $topsites[441] = "ny.gov"; 
    $topsites[442] = "whatsapp.com"; 
    $topsites[443] = "bbt.com"; 
    $topsites[444] = "mozilla.org"; 
    $topsites[445] = "theblaze.com"; 
    $topsites[446] = "crunchyroll.com"; 
    $topsites[447] = "qq.com"; 
    $topsites[448] = "tomshardware.com"; 
    $topsites[449] = "usmagazine.com"; 
    $topsites[450] = "photobucket.com"; 
    $topsites[451] = "digitaltrends.com"; 
    $topsites[452] = "slideshare.net"; 
    $topsites[453] = "nhl.com"; 
    $topsites[454] = "dealnews.com"; 
    $topsites[455] = "careerbuilder.com"; 
    $topsites[456] = "noaa.gov"; 
    $topsites[457] = "fool.com"; 
    $topsites[458] = "kaiserpermanente.org"; 
    $topsites[459] = "salon.com"; 
    $topsites[460] = "6pm.com"; 
    $topsites[461] = "angieslist.com"; 
    $topsites[462] = "state.gov"; 
    $topsites[463] = "cargurus.com"; 
    $topsites[464] = "shutterstock.com"; 
    $topsites[465] = "earthlink.net"; 
    $topsites[466] = "nbc.com"; 
    $topsites[467] = "thewatchseries.to"; 
    $topsites[468] = "bizjournals.com"; 
    $topsites[469] = "nfl.com"; 
    $topsites[470] = "backpage.com"; 
    $topsites[471] = "humblebundle.com"; 
    $topsites[472] = "thehill.com"; 
    $topsites[473] = "genius.com"; 
    $topsites[474] = "change.org"; 
    $topsites[475] = "indiatimes.com"; 
    $topsites[476] = "nasa.gov"; 
    $topsites[477] = "duckduckgo.com"; 
    $topsites[478] = "hsn.com"; 
    $topsites[479] = "timeanddate.com"; 
    $topsites[480] = "ksl.com"; 
    $topsites[481] = "meaww.com"; 
    $topsites[482] = "pizzahut.com"; 
    $topsites[483] = "nexusmods.com"; 
    $topsites[484] = "harvard.edu"; 
    $topsites[485] = "geico.com"; 
    $topsites[486] = "shareasale.com"; 
    $topsites[487] = "nymag.com"; 
    $topsites[488] = "lds.org"; 
    $topsites[489] = "dhs.gov"; 
    $topsites[490] = "basecamp.com"; 
    $topsites[491] = "regions.com"; 
    $topsites[492] = "libraryreserve.com"; 
    $topsites[493] = "teryez.com"; 
    $topsites[494] = "newyorker.com"; 
    $topsites[495] = "naver.com"; 
    $topsites[496] = "travelocity.com"; 
    $topsites[497] = "w3schools.com"; 
    $topsites[498] = "state.tx.us"; 
    $topsites[499] = "abs-cbn.com";
	
	// This For Loop is Beginning at 1 instead of 0 Because I Already Manually Entered in The First Site (google.com)
	/* COMMENTED OUT BECAUSE THIS WAS ALREADY UPDATED IN THE DATABASE
	for ($i = 1; $i <= 25; $i++) {
	    $SQL = "INSERT INTO " . $alphabet[$i] . "LocationTable VALUES (0);";
	    $MySQL->query($SQL);
	}
	*/
	
	// ${$alphabet[6]} = 1; because I Manually Entered in google.com To the Database
	${$alphabet[6]} = 1;
	
	// This For Loop is Beginning at 1 instead of 0 Because I Already Manually Entered in The First Site (google.com)
	for ($ii = 1; $ii <= 25; $ii++) {
	    // If Statement Below is Skipped Because google.com Was Entered Manually Into the Database
	    if ($ii == 6) {
		    continue;
		}
	    ${$alphabet[$ii]} = 0;
	}
	
	// This For Loop is Beginning at 1 instead of 0 Because I Already Manually Entered in The First Site (google.com)
	for ($ii = 1; $ii <= 499; $ii++) {
	    switch ($topsites[$ii][0]) {
			case $alphabet[0]: 
			    ${$alphabet[0]}++;
				$indexNum = ${$alphabet[0]};
				$letterVar = $alphabet[0];
				break;
			case $alphabet[1]: 
			    ${$alphabet[1]}++;
				$indexNum = ${$alphabet[1]};
				$letterVar = $alphabet[1];
				break;
			case $alphabet[2]: 
			    ${$alphabet[2]}++;
				$indexNum = ${$alphabet[2]};
				$letterVar = $alphabet[2];
				break;
			case $alphabet[3]: 
			    ${$alphabet[3]}++;
				$indexNum = ${$alphabet[3]};
				$letterVar = $alphabet[3];
				break;
			case $alphabet[4]: 
			    ${$alphabet[4]}++;
				$indexNum = ${$alphabet[4]};
				$letterVar = $alphabet[4];
				break;
			case $alphabet[5]: 
			    ${$alphabet[5]}++;
				$indexNum = ${$alphabet[5]};
				$letterVar = $alphabet[5];
				break;
			case $alphabet[6]: 
			    ${$alphabet[6]}++;
				$indexNum = ${$alphabet[6]};
				$letterVar = $alphabet[6];
				break;
		    case $alphabet[7]: 
			    ${$alphabet[7]}++;
				$indexNum = ${$alphabet[7]};
				$letterVar = $alphabet[7];
				break;
			case $alphabet[8]: 
			    ${$alphabet[8]}++;
				$indexNum = ${$alphabet[8]};
				$letterVar = $alphabet[8];
				break;
			case $alphabet[9]: 
			    ${$alphabet[9]}++;
				$indexNum = ${$alphabet[9]};
				$letterVar = $alphabet[9];
				break;
			case $alphabet[10]: 
			    ${$alphabet[10]}++;
				$indexNum = ${$alphabet[10]};
				$letterVar = $alphabet[10];
				break;
			case $alphabet[11]: 
			    ${$alphabet[11]}++;
				$indexNum = ${$alphabet[11]};
				$letterVar = $alphabet[11];
				break;
			case $alphabet[12]: 
			    ${$alphabet[12]}++;
				$indexNum = ${$alphabet[12]};
				$letterVar = $alphabet[12];
				break;
			case $alphabet[13]: 
			    ${$alphabet[13]}++;
				$indexNum = ${$alphabet[13]};
				$letterVar = $alphabet[13];
				break;
			case $alphabet[14]: 
			    ${$alphabet[14]}++;
				$indexNum = ${$alphabet[14]};
				$letterVar = $alphabet[14];
				break;
			case $alphabet[15]: 
			    ${$alphabet[15]}++;
				$indexNum = ${$alphabet[15]};
				$letterVar = $alphabet[15];
				break;
			case $alphabet[16]: 
			    ${$alphabet[16]}++;
				$indexNum = ${$alphabet[16]};
				$letterVar = $alphabet[16];
				break;
			case $alphabet[17]: 
			    ${$alphabet[17]}++;
				$indexNum = ${$alphabet[17]};
				$letterVar = $alphabet[17];
				break;
			case $alphabet[18]: 
			    ${$alphabet[18]}++;
				$indexNum = ${$alphabet[18]};
				$letterVar = $alphabet[18];
				break;
			case $alphabet[19]: 
			    ${$alphabet[19]}++;
				$indexNum = ${$alphabet[19]};
				$letterVar = $alphabet[19];
				break;
			case $alphabet[20]: 
			    ${$alphabet[20]}++;
				$indexNum = ${$alphabet[20]};
				$letterVar = $alphabet[20];
				break;
			case $alphabet[21]: 
			    ${$alphabet[21]}++;
				$indexNum = ${$alphabet[21]};
				$letterVar = $alphabet[21];
				break;
			case $alphabet[22]: 
			    ${$alphabet[22]}++;
				$indexNum = ${$alphabet[22]};
				$letterVar = $alphabet[22];
				break;
			case $alphabet[23]: 
			    ${$alphabet[23]}++;
				$indexNum = ${$alphabet[23]};
				$letterVar = $alphabet[23];
				break;
			case $alphabet[24]: 
			    ${$alphabet[24]}++;
				$indexNum = ${$alphabet[24]};
				$letterVar = $alphabet[24];
				break;
			case $alphabet[25]: 
			    ${$alphabet[25]}++;
				$indexNum = ${$alphabet[25]};
				$letterVar = $alphabet[25];
				break;
		}
	    
		
	    $SQL = "INSERT INTO " . $letterVar ."DomainTable VALUES (" . $indexNum . ", '" . $topsites[$ii] . "', 'false', 'false');";
	    $MySQL->query($SQL);
		
		
		// Update LocationTable Value
		$SQL = "UPDATE " . $letterVar . "LocationTable SET lastIdScraped = 0;";
	    $MySQL->query($SQL);
	}
	
	echo "DATABASE SEEDED";
		
$MySQL->close(); ?>
